name: Website Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Website
        run: |
          curl -L https://www.google.com > page.html

      - name: Show File Size
        run: |
          ls -lh page.html