name: Website Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show websites being monitored
        run: |
          echo "Reading monitors.json"
          cat monitors.json